language: android
sudo: false # faster builds
jdk: oraclejdk8
#env:
  #global:
    #- ANDROID_ABI=armeabi-v7a
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Support library
    - extra-android-support
    - extra-android-m2repository

    # system image to run emulator(s) during your tests
    #- sys-img-x86_64-android-25
    #- sys-img-x86_64-android-27

before_install:
    - wget http://services.gradle.org/distributions/gradle-4.4-all.zip
    - unzip gradle-4.4-all.zip
    - export GRADLE_HOME=$PWD/gradle-4.4
    - export PATH=$GRADLE_HOME/bin:$PATH
    #- yes | sdkmanager "platforms;android-27"
    #- pwd
    #- chmod +x gradlew

script:
    #- ./gradlew build jacocoTestReport assembleAndroidTest
    #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    #- emulator -avd test -no-skin -no-audio -no-window &
    #- android-wait-for-emulator
    #- adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
    - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)